=== tmiskell/CapstoneProject/gesture_data/gesture_data.dtd
<!ELEMENT gestures (gesture+, converted-text, status, version)>
<!ELEMENT converted-text (#PCDATA)*>
<!ELEMENT status (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT gesture (hand, hand)>
<!ELEMENT hand (thumb, index, middle, ring, pinky, thumb-index, index-middle, middle-ring, ring-pinky, lsm303+, lsm9dof+)>
<!ATTLIST hand side (left | right) #REQUIRED>
<!ELEMENT thumb (flex, contact-tip)>
<!ELEMENT index (flex, contact-tip, contact-mid)>
<!ELEMENT middle (flex, contact-tip, contact-mid)>
<!ELEMENT ring (flex, contact-tip, contact-mid)>
<!ELEMENT pinky (flex, contact-tip, contact-mid)>
<!ELEMENT thumb-index (contact-tip)>
<!ELEMENT index-middle (contact-tip)>
<!ELEMENT middle-ring (contact-tip)>
<!ELEMENT ring-pinky (contact-tip)>
<!ELEMENT lsm303 (accel-x, accel-y, accel-z, mag-x, mag-y, mag-z)>
<!ATTLIST lsm303 side (top | bottom) #REQUIRED>
<!ELEMENT lsm9dof (accel-x, accel-y, accel-z, mag-x, mag-y, mag-z, gyro-x, gyro-y, gyro-z)>
<!ATTLIST lsm9dof side (top | bottom) #REQUIRED>
<!ELEMENT flex (#PCDATA)>
<!ELEMENT contact-tip (#PCDATA)>
<!ELEMENT contact-mid (#PCDATA)>
<!ELEMENT accel-x (#PCDATA)>
<!ELEMENT accel-y (#PCDATA)>
<!ELEMENT accel-z (#PCDATA)>
<!ELEMENT mag-x (#PCDATA)>
<!ELEMENT mag-y (#PCDATA)>
<!ELEMENT mag-z (#PCDATA)>
<!ELEMENT gyro-x (#PCDATA)>
<!ELEMENT gyro-y (#PCDATA)>
<!ELEMENT gyro-z (#PCDATA)>

=== tmiskell/CapstoneProject/gesture_data/alphabet_xml/J2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="gesture_data.xsl"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
			</thumb>
			<index>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</index>
			<middle>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</middle>
			<ring>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</ring>
			<pinky>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</pinky>
			<thumb-index>
				<contact-tip>false</contact-tip>
			</thumb-index>
			<index-middle>
				<contact-tip>false</contact-tip>
			</index-middle>
			<middle-ring>
				<contact-tip>false</contact-tip>
			</middle-ring>
			<ring-pinky>
				<contact-tip>false</contact-tip>
			</ring-pinky>
			<lsm303 side="top">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
			</lsm303>
			<lsm303 side="bottom">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
			</lsm303>
			<lsm9dof side="top">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
				<gyro-x>0</gyro-x>
				<gyro-y>0</gyro-y>
				<gyro-z>0</gyro-z>
			</lsm9dof>
			<lsm9dof side="bottom">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
				<gyro-x>0</gyro-x>
				<gyro-y>0</gyro-y>
				<gyro-z>0</gyro-z>
			</lsm9dof>
		</hand>
		<hand side="right">
			<thumb>
				<flex>0</flex>
				<contact-tip>false</contact-tip>
			</thumb>
			<index>
				<flex>95</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</index>
			<middle>
				<flex>70</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</middle>
			<ring>
				<flex>95</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</ring>
			<pinky>
				<flex>5</flex>
				<contact-tip>false</contact-tip>
				<contact-mid>false</contact-mid>
			</pinky>
			<thumb-index>
				<contact-tip>false</contact-tip>
			</thumb-index>
			<index-middle>
				<contact-tip>true</contact-tip>
			</index-middle>
			<middle-ring>
				<contact-tip>true</contact-tip>
			</middle-ring>
			<ring-pinky>
				<contact-tip>false</contact-tip>
			</ring-pinky>
			<lsm303 side="top">
				<accel-x>-976</accel-x>
				<accel-y>-24</accel-y>
				<accel-z>-300</accel-z>
				<mag-x>518</mag-x>
				<mag-y>-362</mag-y>
				<mag-z>78</mag-z>
			</lsm303>
			<lsm303 side="bottom">
				<accel-x>-976</accel-x>
				<accel-y>-12</accel-y>
				<accel-z>32</accel-z>
				<mag-x>615</mag-x>
				<mag-y>-198</mag-y>
				<mag-z>200</mag-z>
			</lsm303>
			<lsm9dof side="top">
				<accel-x>-17258</accel-x>
				<accel-y>1258</accel-y>
				<accel-z>-4654</accel-z>
				<mag-x>2983</mag-x>
				<mag-y>1804</mag-y>
				<mag-z>-2482</mag-z>
				<gyro-x>120</gyro-x>
				<gyro-y>490</gyro-y>
				<gyro-z>-243</gyro-z>
			</lsm9dof>
			<lsm9dof side="bottom">
				<accel-x>-16980</accel-x>
				<accel-y>-21</accel-y>
				<accel-z>-7617</accel-z>
				<mag-x>4823</mag-x>
				<mag-y>4489</mag-y>
				<mag-z>-1366</mag-z>
				<gyro-x>73</gyro-x>
				<gyro-y>110</gyro-y>
				<gyro-z>-316</gyro-z>
			</lsm9dof>
		</hand>
	</gesture>
		<converted-text></converted-text>
	<status>connected</status>
	<version>1.0</version>
</gestures>

=== tmiskell/CapstoneProject/gesture_data/gesture_data_init.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="gesture_data.xsl"?>
<!DOCTYPE gestures SYSTEM "gesture_data.dtd">
<gestures>
	<gesture>
		<hand side="left">
			<thumb>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
			</thumb>
			<index>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</index>
			<middle>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</middle>
			<ring>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</ring>
			<pinky>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</pinky>
			<thumb-index>
				<contact-tip>0</contact-tip>
			</thumb-index>
			<index-middle>
				<contact-tip>0</contact-tip>
			</index-middle>
			<middle-ring>
				<contact-tip>0</contact-tip>
			</middle-ring>
			<ring-pinky>
				<contact-tip>0</contact-tip>
			</ring-pinky>
			<lsm303 side="top">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
			</lsm303>
			<lsm303 side="bottom">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
			</lsm303>
			<lsm9dof side="top">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
				<gyro-x>0</gyro-x>
				<gyro-y>0</gyro-y>
				<gyro-z>0</gyro-z>
			</lsm9dof>
			<lsm9dof side="bottom">
				<accel-x>0</accel-x>
				<accel-y>0</accel-y>
				<accel-z>0</accel-z>
				<mag-x>0</mag-x>
				<mag-y>0</mag-y>
				<mag-z>0</mag-z>
				<gyro-x>0</gyro-x>
				<gyro-y>0</gyro-y>
				<gyro-z>0</gyro-z>
			</lsm9dof>
		</hand>
		<hand side="right">
			<thumb>
				<flex>0</flex>
				<contact-tip>0</contact-tip>
			</thumb>
			<index>
				<flex>65</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</index>
			<middle>
				<flex>70</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</middle>
			<ring>
				<flex>90</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</ring>
			<pinky>
				<flex>75</flex>
				<contact-tip>0</contact-tip>
				<contact-mid>0</contact-mid>
			</pinky>
			<thumb-index>
				<contact-tip>0</contact-tip>
			</thumb-index>
			<index-middle>
				<contact-tip>0</contact-tip>
			</index-middle>
			<middle-ring>
				<contact-tip>0</contact-tip>
			</middle-ring>
			<ring-pinky>
				<contact-tip>0</contact-tip>
			</ring-pinky>
			<lsm303 side="top">
				<accel-x>-600</accel-x>
				<accel-y>436</accel-y>
				<accel-z>688</accel-z>
				<mag-x>598</mag-x>
				<mag-y>-147</mag-y>
				<mag-z>-283</mag-z>
			</lsm303>
			<lsm303 side="bottom">
				<accel-x>-220</accel-x>
				<accel-y>332</accel-y>
				<accel-z>892</accel-z>
				<mag-x>465</mag-x>
				<mag-y>-65</mag-y>
				<mag-z>-272</mag-z>
			</lsm303>
			<lsm9dof side="top">
				<accel-x>-7982</accel-x>
				<accel-y>4788</accel-y>
				<accel-z>14619</accel-z>
				<mag-x>3110</mag-x>
				<mag-y>4820</mag-y>
				<mag-z>4664</mag-z>
				<gyro-x>116</gyro-x>
				<gyro-y>451</gyro-y>
				<gyro-z>-233</gyro-z>
			</lsm9dof>
			<lsm9dof side="bottom">
				<accel-x>-8092</accel-x>
				<accel-y>-2467</accel-y>
				<accel-z>14405</accel-z>
				<mag-x>4004</mag-x>
				<mag-y>8389</mag-y>
				<mag-z>3529</mag-z>
				<gyro-x>79</gyro-x>
				<gyro-y>142</gyro-y>
				<gyro-z>-425</gyro-z>
			</lsm9dof>
		</hand>
	</gesture>
		<converted-text></converted-text>
	<status>connected</status>
	<convert>false</convert>
	<version>1.0</version>
</gestures>
